sonar.projectKey=dandoetech_package-skeleton
sonar.organization=dandoetech
sonar.projectName=DanDoeTech PackageSkeleton
sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage/clover.xml
sonar.sourceEncoding=UTF-8
